services:
  democicd:
    image: ${DOCKER_REGISTRY-}democicd
    build:
      context: .
      dockerfile: DemoCICD/Dockerfile

  democicdworker:
    image: ${DOCKER_REGISTRY-}democicdworker
    build:
      context: .
      dockerfile: DemoCICDWorker/Dockerfile

